### PR TITLE
Release 1.6.0

### LINKED ISSUE #21: Getting 'Unknown Kotlin JVM target: 21' error if we build with JDK 21.
### Description
In new Android Studio(Ladybug | 2024.2.1 Patch 1 which released on Build #AI-242.23339.11.2421.12483815, built on October 11, 2024) default android gradle JDK version set to 21. When we add this plugin and try to run the app getting below error.

org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':capacitor-freerasp:compileDebugKotlin'.
Caused by: java.lang.IllegalArgumentException: Unknown Kotlin JVM target: 21

### To Reproduce
Add this plugin to ionic capacitor project.
Update gradle JDK to 21
Build the app.
Expected behavior
We should not get any kotlin compatable error with JDK 21

### Please complete the following information:
Build issue.
Version of freeRASP:1.4.0, 1.5.2

### Additional context
At least add below kotlin options in the plugin gradle.
kotlinOptions { jvmTarget = "17" }

### PR DESCRIPTION
**Pull request by tompsota**
# What's new
_Describe the PR shortly_

# PR checklist

## In-app checks:
- [x] callbacks are received
- [x] dev/prod switch works
- [x] `README.md` is updated _(if applicable)_
- [x] `example` app is working

## Pre-release checks:

- [x] `CHANGELOG.md` is updated
- [x] `package.json` version is increased
- [x] `release` label is applied on PR

### To be checked by maintainers:

- [x] freeRASP logs are received
- [x] `sdkVersion` property in logs is correct
- [x] `sdkPlatform` property in logs is correct

# Resolved issues
_list of issues resolved by this PR_
closes #21

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -43,10 +44,25 @@ const prepareMapping = async (): Promise<void> => {
   });
 };
 
+// parses base64-encoded malware data to SuspiciousAppInfo[]
+const parseMalwareData = (data: string[]): SuspiciousAppInfo[] => {
+  const result: SuspiciousAppInfo[] = [];
+  data.forEach(entry => {
+    result.push(toSuspiciousAppInfo(entry));
+  });
+  return result;
```
Comment (tomasbilos) [inline src/index.ts:53]: Tu by si mohol skusiť či by nešlo
`data.map(entry => toSuspiciousAppInfo(entry))`

File: example/src/pages/FreeRaspDemo.tsx [hunk 2]
```diff
@@ -17,12 +17,39 @@ import {
...
+    appsToWhitelist.forEach(async app => {
+      try {
+        const whitelistResponse = await addToWhitelist(app);
+        console.info(
+          `${app} stored to Malware Whitelist: ${whitelistResponse}`,
+        );
+      } catch (error: any) {
+        console.info('Malware whitelist failed: ', error);
+      }
+    });
```
Comment (tomasbilos) [inline example/src/pages/FreeRaspDemo.tsx:50]:
```suggestion
    const promises = appsToWhitelist.map(async app => {
      try {
        const whitelistResponse = await addToWhitelist(app);
        console.info(
          `${app} stored to Malware Whitelist: ${whitelistResponse}`,
        );
      } catch (error: any) {
        console.info('Malware whitelist failed: ', error);
      }
    });
    await Promise.all(promises);
```
